### ISSUE TITLE
Version 6.7.0 Swift Module Install Issue

### ISSUE THREAD

**Issue by kexoth** [dbgrandi/Flurry#51]
Before that I used the version 6.6.0 in my Swift project with `use_frameworks!` & because it wasn't defined as a module I just added in my bridging header `#import <Flurry.h>`.

Now that approach doesn't work with version 6.7.0 & I noticed that Flurry now functions as a module, but I got:

    Undefined symbols for architecture x86_64:
    "_OBJC_CLASS_$_Flurry", referenced from:
    __TMaCSo6Flurry in KXAnalytics.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any idea why this might be happening?

I tried cleaning up everything I'm aware of, derived data, reinstalled everything, but still nothing.

Thanks,

@kexoth

**Comment by dbgrandi** [comment]
I'm going to close this because [Flurry is releasing an official pod](https://github.com/flurry/Flurry-iOS-SDK) and will be releasing from version 7.0.0 onward. I want to encourage people to move over to that official pod.

In the mean time, did you try the 6.7.1-beta1 release? @brianmichel added a nearly empty `.m` file to force the module to build properly. That may solve your issue.
